org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
# 允许中文路径（项目名为中文）
android.overridePathCheck=true

# 本地代理（clash），解决 mavenCentral / google 依赖下载问题
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897
